/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudyProjectsImport } from './routes/study-projects'
import { Route as SkillsImport } from './routes/skills'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const StudyProjectsRoute = StudyProjectsImport.update({
  id: '/study-projects',
  path: '/study-projects',
  getParentRoute: () => rootRoute,
} as any)

const SkillsRoute = SkillsImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsImport
      parentRoute: typeof rootRoute
    }
    '/study-projects': {
      id: '/study-projects'
      path: '/study-projects'
      fullPath: '/study-projects'
      preLoaderRoute: typeof StudyProjectsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/study-projects': typeof StudyProjectsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/study-projects': typeof StudyProjectsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/skills': typeof SkillsRoute
  '/study-projects': typeof StudyProjectsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/skills' | '/study-projects'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/skills' | '/study-projects'
  id: '__root__' | '/' | '/skills' | '/study-projects'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SkillsRoute: typeof SkillsRoute
  StudyProjectsRoute: typeof StudyProjectsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SkillsRoute: SkillsRoute,
  StudyProjectsRoute: StudyProjectsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/skills",
        "/study-projects"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/skills": {
      "filePath": "skills.jsx"
    },
    "/study-projects": {
      "filePath": "study-projects.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
